### PR TITLE
Bug/#183/redefine home page

### LINKED ISSUE #183: Redefine home page to look exactly like figma
IMG-7020

- “See All” button does not link to vendors page
- Spacing is off (firmly follow figma spacings and design)
- Logout button is covered by phone navbar
- Home page navbar does not show icons

### PR DESCRIPTION
**Pull request by jdrco**
Description:
- Added functionality to the “See All” button to link to vendors page
- Moved "Logout" button below the phone navbar
- Added dynamic icons to the Homepage navbar
- Made basic styling changes to make homepage look more like figma
- Some files were reformatted using "Prettier"

Demo:
image

### CODE REVIEW

File: mobile/App.js [hunk 1]
```diff
@@ -31,66 +35,62 @@ const App = () => {
...
       subscription.remove();
     };
   }, [user]);
- 
-  
-  
+
   return (
-    <SafeAreaView style={{flex: 1}}>
+    <SafeAreaProvider style={{flex: 1}}>
```
Comment (yismailuofa) [inline mobile/App.js:93]: Just curious about what the change from `SafeAreaView` to `SafeAreaProvider` does here? Also we can remove the unused import to `SafeAreaView` at the top then as well,

**Review by yismailuofa — APPROVED** [review]
lgtm

**Comment by yismailuofa** [comment]
Merging @filippociandy10
